# -*- coding: utf-8 -*-
"""DAG generated by pdi2dag v1.17.4 - review before production use.

Source:    C:/Projects/PDI-AirFlow/samples/cscu/cscu_daily_load.kjb
PDI job: cscu_daily_load (repository path /home/cscu/etl/cscu_daily_load)

Migration notes:
  - Entry 'Mail Failure' of type MAIL has no Airflow equivalent and was not migrated - port it manually (e.g. BashOperator, EmailOperator).
"""

import pendulum

from airflow import DAG
from airflow_pentaho.operators.carte import CarteTransOperator

PDI_PARAMS = {
    'since_dt': '2026-07-01',
}

with DAG(
    dag_id='cscu_daily_load',
    description="Migrated from PDI job 'cscu_daily_load'",
    schedule='0 2 * * *',
    start_date=pendulum.datetime(2026, 7, 20, tz='UTC'),
    catchup=False,
    default_args={'owner': 'pdi2dag', 'retries': 0},
    tags=['pdi', 'pdi2dag'],
) as dag:
    Extract_Transactions = CarteTransOperator(
        task_id='Extract_Transactions',
        trans='/home/cscu/etl/extract_transactions',
        pdi_conn_id='pdi_default',
        params=PDI_PARAMS,
        level='Basic',
    )

    Build_Member_Mart = CarteTransOperator(
        task_id='Build_Member_Mart',
        trans='/home/cscu/etl/build_member_mart',
        pdi_conn_id='pdi_default',
        params=PDI_PARAMS,
        level='Basic',
    )

    # Dependencies from PDI hops
    Extract_Transactions >> Build_Member_Mart
