# -*- coding: utf-8 -*-
"""DAG generated by pdi2dag v1.17.4 - review before production use.

Source:    C:/Projects/PDI-AirFlow/samples/cscu/extract_transactions.ktr
PDI transformation: extract_transactions (repository path /home/cscu/etl/extract_transactions)
"""

import pendulum

from airflow import DAG
from airflow_pentaho.operators.carte import CarteTransOperator

PDI_PARAMS = {
    'since_dt': '2026-07-01',
}

with DAG(
    dag_id='extract_transactions',
    description="Migrated from PDI transformation 'extract_transactions'",
    schedule=None,
    start_date=pendulum.datetime(2026, 7, 20, tz='UTC'),
    catchup=False,
    default_args={'owner': 'pdi2dag', 'retries': 0},
    tags=['pdi', 'pdi2dag'],
) as dag:
    run_extract_transactions = CarteTransOperator(
        task_id='run_extract_transactions',
        trans='/home/cscu/etl/extract_transactions',
        pdi_conn_id='pdi_default',
        params=PDI_PARAMS,
        level='Basic',
    )
