# -*- coding: utf-8 -*-
"""DAG generated by pdi2dag v1.17.4 - review before production use.

Source:    C:/Projects/PDI-AirFlow/samples/cscu/build_member_mart.ktr
PDI transformation: build_member_mart (repository path /home/cscu/etl/build_member_mart)
"""

import pendulum

from airflow import DAG
from airflow_pentaho.operators.carte import CarteTransOperator

PDI_PARAMS = {
}

with DAG(
    dag_id='build_member_mart',
    description="Migrated from PDI transformation 'build_member_mart'",
    schedule=None,
    start_date=pendulum.datetime(2026, 7, 20, tz='UTC'),
    catchup=False,
    default_args={'owner': 'pdi2dag', 'retries': 0},
    tags=['pdi', 'pdi2dag'],
) as dag:
    run_build_member_mart = CarteTransOperator(
        task_id='run_build_member_mart',
        trans='/home/cscu/etl/build_member_mart',
        pdi_conn_id='pdi_default',
        params=PDI_PARAMS,
        level='Basic',
    )
