# -*- coding: utf-8 -*-
"""DAG generated by pdi2dag v1.20.0 - review before production use.

Source:    C:/Projects/PDI-AirFlow/samples/cscu/import_ach_minio.ktr
PDI transformation: import_ach_minio (repository path /CSCU/import_ach_minio)
"""

import pendulum

from airflow import DAG
from airflow_pentaho.operators.carte import CarteTransOperator

PDI_PARAMS = {
}

with DAG(
    dag_id='import_ach_minio',
    description="Migrated from PDI transformation 'import_ach_minio'",
    schedule=None,
    start_date=pendulum.datetime(2026, 7, 20, tz='UTC'),
    catchup=False,
    default_args={'owner': 'pdi2dag', 'retries': 0},
    tags=['pdi', 'pdi2dag'],
) as dag:
    run_import_ach_minio = CarteTransOperator(
        task_id='run_import_ach_minio',
        trans='/CSCU/import_ach_minio',
        pdi_conn_id='pdi_default',
        params=PDI_PARAMS,
        level='Basic',
    )
