# -*- coding: utf-8 -*-
"""DAG generated by pdi2dag v1.21.2 - review before production use.

Source:    C:/PDI-Airflow/pipelines/CSCU/ingest_from_minio.ktr
PDI transformation: ingest_from_minio (repository path /ingest_from_minio)
"""

import pendulum

from airflow import DAG
from airflow_pentaho.operators.carte import CarteTransOperator

PDI_PARAMS = {
}

with DAG(
    dag_id='ingest_from_minio',
    description="Migrated from PDI transformation 'ingest_from_minio'",
    schedule=None,
    start_date=pendulum.datetime(2026, 7, 1, tz='UTC'),
    catchup=False,
    default_args={'owner': 'pdi2dag', 'retries': 0},
    tags=['pdi', 'pdi2dag'],
) as dag:
    run_ingest_from_minio = CarteTransOperator(
        task_id='run_ingest_from_minio',
        trans='/ingest_from_minio',
        pdi_conn_id='pdi_default',
        params=PDI_PARAMS,
        level='Basic',
    )
