# -*- coding: utf-8 -*-
"""DAG generated by pdi2dag v1.21.2 - review before production use.

Source:    C:/PDI-Airflow/pipelines/CSCU/txn_report.ktr
PDI transformation: txn_report (repository path /txn_report)
"""

import pendulum

from airflow import DAG
from airflow_pentaho.operators.carte import CarteTransOperator

PDI_PARAMS = {
}

with DAG(
    dag_id='txn_report',
    description="Migrated from PDI transformation 'txn_report'",
    schedule=None,
    start_date=pendulum.datetime(2026, 7, 1, tz='UTC'),
    catchup=False,
    default_args={'owner': 'pdi2dag', 'retries': 0},
    tags=['pdi', 'pdi2dag'],
) as dag:
    run_txn_report = CarteTransOperator(
        task_id='run_txn_report',
        trans='/txn_report',
        pdi_conn_id='pdi_default',
        params=PDI_PARAMS,
        level='Basic',
    )
