# -*- coding: utf-8 -*-
"""DAG generated by pdi2dag v1.2.0 — review before production use.

Source:    mini_job.kjb
PDI job: mini_job (repository path /demo/mini_job)
"""

import pendulum

from airflow import DAG
from airflow_pentaho.operators.carte import CarteTransOperator

PDI_PARAMS = {
    'date': '{{ ds }}',
}

with DAG(
    dag_id='mini_job',
    description="Migrated from PDI job 'mini_job'",
    schedule='0 6 * * *',
    start_date=pendulum.datetime(2026, 7, 18, tz='UTC'),
    catchup=False,
    default_args={'owner': 'pdi2dag', 'retries': 0},
    tags=['pdi', 'pdi2dag'],
) as dag:
    Extract_Sales = CarteTransOperator(
        task_id='Extract_Sales',
        trans='/demo/extract_sales',
        pdi_conn_id='pdi_default',
        params=PDI_PARAMS,
        level='Basic',
        deferrable=True,
        poll_interval=10,
    )

    Load_DW = CarteTransOperator(
        task_id='Load_DW',
        trans='/demo/load_warehouse',
        pdi_conn_id='pdi_default',
        params=PDI_PARAMS,
        level='Basic',
        deferrable=True,
        poll_interval=10,
    )

    # Dependencies from PDI hops
    Extract_Sales >> Load_DW
